// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyarsdvghzafouufchsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5YXJzZHZnaHphZm91dWZjaHNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA0NzA3NTIsImV4cCI6MjA5NjA0Njc1Mn0.Gp6AlBdzKa2QLxDykOFzn0RDdnFqAMpkB4woSQ8UDeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);